---
name: 'Build storybook and pack npm package'

on:
  workflow_call:

jobs:
  build-storybook:
    name: Build storybook page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm -w @lotta-schule/theme run build
      - run: npm -w @lotta-schule/storybook-addon-theme run build
      - run: npm run storybook:build
        env:
          STORYBOOK_BASE_HREF: /${{ github.event.repository.name }}
      - run: tar -czf storybook.tgz --directory=storybook-static .
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: storybook-static
          path: storybook.tgz

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm pack
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: npm-package
          path: lotta-schule-hubert*.tgz
          if-no-files-found: error
