---
name: 'Check that a tag for the version is still available'

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: false
        default: .
    outputs:
      version-name:
        description: 'The version of the package, as read from package.json'
        value: ${{ jobs.check-version-name-tag.outputs.version-name }}

jobs:
  check-version-name-tag:
    runs-on: ubuntu-latest
    outputs:
      version-name: ${{ steps.read-version.outputs.version-name }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Read version from package.json
        run: |
          export VERSION_NAME=$(node -p 'require("${{ inputs.path }}/package.json").version')
          echo "version detected in package.json: $VERSION_NAME"
          echo "version-name=$VERSION_NAME" >> $GITHUB_OUTPUT
        id: read-version
      - name: Check that tag does not exist
        run: |
          [ -z $(git tag -l "${{ steps.read-version.outputs.version-name }}") ]
