---
name: 'Push the npm package and deploy Storybook to gh page'

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      tag-name:
        required: false
        type: string
    secrets:
      npm-token:
        required: true

jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/download-artifact@v3
        with:
          name: npm-package

      - name: publish to npm
        run: |
          npm publish lotta-schule-hubert*.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Create and push tag
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ inputs.tag-name || inputs.version }}",
              sha: context.sha
            })

  deploy-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: storybook-static

      - name: Untar storybook packages
        run: |
          mkdir -p storybook
          tar -xzf storybook.tgz -C storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook
