---
name: 'Build storybook and pack npm package'

on:
  workflow_run:
    workflows:
      - Run checks and tests
    types:
      - completed

jobs:
  build-storybook:
    name: Build storybook page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm -w @lotta-schule/theme run build
      - run: npm -w @lotta-schule/storybook-addon-theme run build
      - run: npm run build
        env:
          STORYBOOK_BASE_HREF: /${{ github.event.repository.name }}
      - run: tar -czf storybook.tgz --directory=storybook-static .
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: Storybook Static Site Documentation
          path: storybook.tgz

  package:
    runs-on: ubuntu-latest
    needs:
      - build-storybook
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm pack
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: npm package
          path: lotta-schule-hubert*.tgz
          if-no-files-found: error
