name: CI

on:
  push:
    paths-ignore:
      - 'packages/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: npm ci
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: npm ci
      - run: npm test -- --ci --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: './coverage'
          fail_ci_if_error: false
          move_coverage_to_trash: true
          verbose: true
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run typecheck
  storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm -w @lotta-schule/storybook-addon-theme run build
      - run: npm run build
        env:
          STORYBOOK_BASE_HREF: /${{ github.event.repository.name }}
      - run: tar -czf storybook.tgz --directory=storybook-static .
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: Storybook Static Site Documentation
          path: storybook.tgz
          if-no-files-found: error
  pack:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - typecheck
      - storybook
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm pack
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: npm package
          path: lotta-schule-hubert*.tgz
          if-no-files-found: error

