name: 'Storybook Addon: Theme - CI'

on:
  push:
    paths:
      - 'packages/storybook-addon-theme/**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: npm -w @lotta-schule/storybook-addon-theme ci 
      - run: npm -w @lotta-schule/storybook-addon-theme run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm' # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
      - run: npm -w @lotta-schule/storybook-addon-theme ci
      - run: npm -w @lotta-schule/storybook-addon-theme test -- --ci --coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: './packages/storybook-addon-theme/coverage'
          fail_ci_if_error: false
          flags: storybook-addon-theme
          move_coverage_to_trash: true
          verbose: true
  pack:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm -w @lotta-schule/storybook-addon-theme ci
      - run: npm -w @lotta-schule/storybook-addon-theme pack
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: npm package storybook-addon-theme
          path: lotta-schule-storybook-addon-theme*.tgz
          if-no-files-found: error

